# Generated by Django 6.0.2 on 2026-03-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='topic',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
