# Generated by Django 6.0.2 on 2026-03-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quizresult_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='topic',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
